name: win32_gamepad
description: A package that provides a friendly Dart API for accessing gamepads
  connected to a Windows machine.
version: 1.0.9
repository: https://github.com/halildurmus/win32_gamepad
issue_tracker: https://github.com/halildurmus/win32_gamepad/issues

topics:
  - gamepad
  - win32
  - ffi
  - windows

environment:
  sdk: ^3.5.0

platforms:
  windows:

dependencies:
  ffi: ^2.1.3
  win32: ^5.8.0

dev_dependencies:
  checks: ^0.3.0
  hooks:
    git:
      url: https://github.com/halildurmus/workflows.git
      path: packages/hooks
  lints:
    git:
      url: https://github.com/halildurmus/workflows.git
      path: packages/lints
  test: ^1.25.8
